duty/urls.py
from django.urls import path

from duty.views import form
app_name = 'duty'
urlpatterns = [
    path('', form, name='form'),
]

pizza/urls.py
from django.contrib import admin
from django.urls import path
from store.views import (hello_world,
                         index)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello_world),
    path('<int:val>', index, name='index'),
]

smena/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from journal.views import index
from journal import urls as journal_urls
from station import urls as station_urls
from duty import urls as duty_urls
from archive import urls as archive_urls
from staff import urls as staff_urls
from stats import urls as stats_urls

urlpatterns = [
    #
    path('admin/', admin.site.urls),
    # Main pages
    path('', index, name='index'),
    # Add pages
    path('journal/', include(journal_urls, namespace='journal')),
    path('station/', include(station_urls, namespace='station')),
    path('duty/', include(duty_urls, namespace='duty')),
    path('archive/', include(archive_urls, namespace='archive')),
    path('staff/', include(staff_urls, namespace='staff')),
    path('stats/', include(stats_urls, namespace='stats')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

duty/models.py
from django.db import models

from staff.models import Employee, Workplace

# Create your models here.


class Duty(models.Model):
    date = models.DateTimeField()


class DutyStaff(models.Model):
    duty = models.ForeignKey(
        Duty,
        on_delete=models.CASCADE,
    )
    employee = models.ForeignKey(
        Employee,
        on_delete=models.CASCADE,
    )
    workplace = models.ForeignKey(
        Workplace,
        on_delete=models.CASCADE,
    )

duty/forms.py
from django import forms

from staff.models import Employee, Workplace


class DutyForm(forms.Form):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)

        workplaces = Workplace.objects.filter(organization__abbr='КТЦ')
        for workplace in workplaces:
            self.fields[str(workplace.id)] = forms.ModelChoiceField(
                queryset=Employee.objects.filter(organization__abbr='КТЦ'),
                label=str(workplace.name)
            )
            self.fields[str(workplace.id)].widget.attrs.update({
            'class': 'uk-select uk-form-width-medium uk-display-block'})

        workplaces = Workplace.objects.filter(organization__abbr='ЦУП')
        for workplace in workplaces:
            self.fields[str(workplace.id)] = forms.ModelChoiceField(
                queryset=Employee.objects.filter(organization__abbr='ЦУП'),
                label=str(workplace.name)
            )
            self.fields[str(workplace.id)].widget.attrs.update({
            'class': 'uk-select uk-form-width-medium uk-display-block'})

duty/views.py
from datetime import datetime

from django.contrib import messages
from django.shortcuts import render, redirect
from django.db import transaction
from django.http import HttpResponse

from duty.forms import DutyForm
from duty.models import Duty, DutyStaff
from staff.models import Employee, Workplace
from . import DisplayMessages


# Create your views here.
def form(request):
    data = {
        'form': DutyForm()
    }
    if request.method == 'GET':
        return render(request, 'duty/form.html', data)
    elif request.method == 'POST':
        form = DutyForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                duty = Duty(date=datetime.now())
                duty.save()
                for key, value in form.cleaned_data.items():
                    employee = Employee.objects.get(id=value.pk)
                    workplace = Workplace.objects.get(id=int(key))
                    duty_staff = DutyStaff(duty=duty, employee=employee, workplace=workplace)
                    duty_staff.save()
            messages.success(request, DisplayMessages.DUTY_SAVE)
            return redirect('index')
        else:
            return render(request, 'duty/form.html', data)
    return HttpResponse(status=405)

duty/templates/duty/duty.html
{% if duty == False %}
    <a class="uk-button uk-button-danger uk-width-1-1 uk-padding-remove" href="{% url 'duty:form' %}">Добавить
        дежурство</a>
{% else %}
    <div class="uk-card uk-card-default uk-card-body">
        <h5 class="uk-text-uppercase">Дежурство</h5>
        <ul class="uk-list uk-list-divider">
            {% for employee in duty %}
                <li>
                    <p class="uk-margin-remove-bottom uk-text-break">{{ employee.employee.surname }} {{ employee.employee.name }} {{ employee.employee.patronymic }}</p>
                    <div class="uk-text-meta uk-panel uk-panel-box uk-text-truncate"><span
                            class="uk-margin-small-right"
                            uk-icon="icon: receiver; ratio: 0.8"
                            uk-tooltip="тел. {{ employee.workplace.telefon }}"></span>{{ employee.workplace.name }}
                    </div>
                </li>

            {% endfor %}
        </ul>
        <a href="#"></span>Редактировать дежурство</a>
    </div>
{% endif %}

duty/templates/duty/form.html
{% extends "index.html" %}
{% block title %}Дежурство{% endblock %}
{% block content %}
    <div class="uk-section-small uk-padding-remove-top">
        <h4 class="uk-text-uppercase">Добавить дежурство</h4>
        <div class="uk-card uk-card-default uk-card-body">
            <form action="{% url 'duty:form' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="uk-button uk-button-primary" type="submit" value="Добавить" >
            </form>
        </div>
    </div>
{% endblock %}