duty/urls.py
from django.urls import path

from duty.views import form
app_name = 'duty'
urlpatterns = [
    path('', form, name='form'),
]

pizza/urls.py
from django.contrib import admin
from django.urls import path
from store.views import (hello_world,
                         index)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello_world),
    path('<int:val>', index, name='index'),
]

smena/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from journal.views import index
from journal import urls as journal_urls
from station import urls as station_urls
from duty import urls as duty_urls
from archive import urls as archive_urls
from staff import urls as staff_urls
from stats import urls as stats_urls

urlpatterns = [
    #
    path('admin/', admin.site.urls),
    # Main pages
    path('', index, name='index'),
    # Add pages
    path('journal/', include(journal_urls, namespace='journal')),
    path('station/', include(station_urls, namespace='station')),
    path('duty/', include(duty_urls, namespace='duty')),
    path('archive/', include(archive_urls, namespace='archive')),
    path('staff/', include(staff_urls, namespace='staff')),
    path('stats/', include(stats_urls, namespace='stats')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

templates/index.html
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Домашняя страница{% endblock title %}</title>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="uk-navbar-container">
    <div class="uk-container uk-container-small">
        <nav class="uk-navbar" uk-navbar>
            <div class="uk-navbar-left">
                <a class="uk-navbar-item uk-logo" href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}"
                                                                                alt="Смена"></a>
                <ul class="uk-navbar-nav">
                    <li><a href="{% url 'index' %}">Главная</a></li>
                    <li><a href="{% url 'archive:index' %}">Архив</a></li>
                    <li><a href="{% url 'stats:index' %}">Статистика</a></li>
                    
                </ul>
            </div>

            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav">
                    <li>
                            <a href="#">Справка</a>
                            <div class="uk-navbar-dropdown">
                                <ul class="uk-nav uk-navbar-dropdown-nav">
                                        <li><a href="{% url 'staff:index' %}">Сотрудники</a></li>
                                        <li><a href="{% url 'station:index' %}">Станции</a></li>
                                        <li><a href="#">Помощь</a></li>
                                </ul>
                            </div>
                        </li>
                    
                </ul>
            </div>
        </nav>
    </div>
</div>

<div class="uk-container uk-container-small">
    {% if messages %}
        {% include 'messages.html' %}
    {% endif %}

    <div class="uk-section-small">
        <div uk-grid>
            <div class="uk-width-2-3">
                {% block content %}
                    {% include 'journal/page.html' %}
                {% endblock content %}
            </div>
            <div class="uk-width-1-3">
                <p uk-margin>
                    <a class="uk-button uk-button-primary uk-width-1-1" href="{% url 'journal:add/write-down' %}">Добавить
                        запись</a>
                </p>
                {% include 'duty/duty.html' %}
            </div>

        </div>
    </div>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/uikit.min.js' %}"></script>
<script src="{% static 'js/uikit-icons.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/messages.html
<div class="uk-section-xsmall uk-padding-remove-bottom">
    {% for message in messages %}
        <div class="{{ message.tags }} uk-margin-remove-bottom" uk-alert>
            <a class="uk-alert-close" uk-close></a>
            <p>{{ message }}</p>
        </div>
    {% endfor %}

</div>